### ISSUE TITLE
Website tool no longer available for Linux

### ISSUE THREAD

**Issue by poirier** [jaymzh/concordance#6]
I just discovered that http://members.harmonyremote.com/ is gone. There's a new site at https://setup.myharmony.com/ that if you poke around, you can almost get to a web configuration tool, but it refuses to run for a browser on Linux.  By faking an IE useragent, I managed to get a page or two into it and create a new myharmony account, but then it wanted me to install Microsoft Silverlight...

This is obviously not a bug with concordance. But this seems like as good a place as any to see if a workaround can be found and share it.

**Comment by swt2c** [comment]
I think there must be some kind of unplanned outage, since that just looks like some default IIS page, rather than a "hey, go here instead" type thing.

On the remotes that use setup.myharmony.com, you can use MHGUI, which is part of Congruity: https://sourceforge.net/projects/congruity/

**Comment by jaymzh** [comment]
On 07/29/2015 08:18 PM, Scott Talbert wrote:

> I think there must be some kind of unplanned outage, since that just looks
> like some default IIS page, rather than a "hey, go here instead" type thing.

I was going to say the same thing - it doesn't look like an intentional shut
down. However, they've been saying "your software is out of date" on that site
for anyone accessing it directly forever, so it's possible. Hopefully it'll be
back soon though.

## 

Phil Dibowitz                             phil@ipom.com
Open Source software and tech docs        Insanity Palace of Metallica
http://www.phildev.net/                   http://www.ipom.com/

"Be who you are and say what you feel, because those who mind don't matter
 and those who matter don't mind."
- Dr. Seuss

**Comment by swt2c** [comment]
OK, so I noticed the site still showed the same thing, so I dug a little deeper.  It looks like if you go to http://members.harmonyremote.com/EasyZapper/ you can get the familiar site.  It seems that maybe they used to have a redirect on the root page, but it is gone now?

**Comment by poirier** [comment]
Thanks swt2c, that URL still seems to work!  (I wonder for how much longer, but for now it looks like we'll still be able to use concordance.)

**Comment by swt2c** [comment]
PR #7 submitted to update documentation.

**Comment by jaymzh** [comment]
PR merged. Closing issue. Thanks guys!
